apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshmart-frontend
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rayaneW/stage_usecase_harvestmart.git
    targetRevision: HEAD
    path: bakery/k8s
    directory:
      recurse: true
      exclude: '{argocd-application.yaml,argocd-application-frontend.yaml,argocd-project.yaml,argocd-rbac.yaml,instana-agent.customresource.yaml,instana-agent-service-redirect.yaml,instana-operator-subscription.yaml,deploy.sh,backend-deployment.yaml,imagestream-backend.yaml,buildconfig-backend.yaml,postgres-cluster.yaml,postgres-initdb.yaml,prometheus-deployment.yaml,grafana-deployment.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: freshmart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true