apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshmart-cloud
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rayaneW/stage_usecase_harvestmart.git
    targetRevision: HEAD
    path: bakery/k8s
    directory:
      recurse: true
      exclude: '{argocd-application.yaml,argocd-application-frontend.yaml,argocd-project.yaml,argocd-rbac.yaml,instana-agent.customresource.yaml,deploy.sh,frontend-deployment.yaml,imagestream-frontend.yaml,buildconfig-frontend.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: freshmart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
