apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bakery-backend
  namespace: freshmart
spec:
  source:
    git:
      uri: https://github.com/rayaneW/stage_usecase_harvestmart.git
      ref: main
    contextDir: bakery/bakery-backend/bakery-backend
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/openjdk-17:1.20
      env:
        - name: MAVEN_ARGS
          value: "-DskipTests clean package"
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/freshmart/bakery-backend:latest
  triggers: []