apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bakery-backend
  namespace: freshmart
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/rayaneW/stage_usecase_harvestmart.git
      ref: main
    contextDir: bakery/bakery-backend/bakery-backend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/freshmart/bakery-backend:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
