apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: harvestmart-frontend
  namespace: freshmart
spec:
  source:
    git:
      uri: https://github.com/rayaneW/stage_usecase_harvestmart.git
      ref: main
    contextDir: bakery/HarvestMart
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/freshmart/harvestmart-frontend:latest
  triggers:
  - type: ConfigChange
