---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: freshmart
data:
  BACKEND_UPSTREAM: "http://bakery-backend-service:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvestmart-frontend
  namespace: freshmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvestmart-frontend
  template:
    metadata:
      labels:
        app: harvestmart-frontend
    spec:
      containers:
        - name: harvestmart-frontend
          image: image-registry.openshift-image-registry.svc:5000/freshmart/harvestmart-frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: BACKEND_UPSTREAM
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: BACKEND_UPSTREAM
---
apiVersion: v1
kind: Service
metadata:
  name: harvestmart-frontend-service
  namespace: freshmart
spec:
  selector:
    app: harvestmart-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: harvestmart-frontend-route
  namespace: freshmart
spec:
  to:
    kind: Service
    name: harvestmart-frontend-service
  port:
    targetPort: 80
