apiVersion: v1
kind: Namespace
metadata:
  name: openshift-instana-operator
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: instana-operator-group
  namespace: openshift-instana-operator
spec:
  targetNamespaces:
  - openshift-instana-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: instana-agent-operator
  namespace: openshift-instana-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: instana-agent-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: instana-agent-operator.v2.2.12
