apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: openshift-operators
spec:
  zone:
    name:  # (optional) name of the zone of the host
  cluster:
      name: openshift-operators
  agent:
    key: O_xPXPnaToa9ZpkiPG0Elg
    downloadKey: O_xPXPnaToa9ZpkiPG0Elg
    endpointHost: ingress-orange-saas.instana.io
    endpointPort: "443"
