apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: freshmart
  namespace: freshmart
spec:
  postgresVersion: 16
  openshift: true
  databaseInitSQL:
    name: freshmart-initdb
  instances:
    - name: instance1
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
